import React, { useState } from 'react';
import { Download, FileText, Loader2, CheckCircle } from 'lucide-react';
import { jsPDF } from 'jspdf';

// ─── helpers ────────────────────────────────────────────────────────────────

function wrap(doc, text, x, y, maxWidth, lineHeight = 7) {
  const lines = doc.splitTextToSize(String(text || ''), maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

function formatTime(seconds) {
  const s = Number(seconds) || 0;
  const m = Math.floor(s / 60);
  const sec = Math.floor(s % 60);
  return `${m}:${sec.toString().padStart(2, '0')}`;
}

// ─── main builder ────────────────────────────────────────────────────────────

function buildPdf({ title, overall, topics, recent }) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210;
  const MARGIN = 18;
  const CONTENT_W = W - MARGIN * 2;
  const PAGE_H = 297;
  const FOOTER_H = 18;
  const SAFE_H = PAGE_H - FOOTER_H - MARGIN;

  let y = 0;

  // ── footer helper ──────────────────────────────────────────────────────────
  function addFooter(pageNum) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.setDrawColor(220, 220, 220);
    doc.line(MARGIN, PAGE_H - FOOTER_H, W - MARGIN, PAGE_H - FOOTER_H);
    doc.text('Generated by Alexandria · learnflow.ai', MARGIN, PAGE_H - 10);
    doc.text(`Page ${pageNum}`, W - MARGIN, PAGE_H - 10, { align: 'right' });
  }

  // ── page guard ─────────────────────────────────────────────────────────────
  let pageNum = 1;
  function checkPage(needed = 12) {
    if (y + needed > SAFE_H) {
      addFooter(pageNum);
      doc.addPage();
      pageNum++;
      y = MARGIN;
    }
  }

  // ─── COVER HEADER ─────────────────────────────────────────────────────────
  // gradient-like top bar
  doc.setFillColor(99, 102, 241);           // indigo-500
  doc.rect(0, 0, W, 38, 'F');

  doc.setFillColor(20, 184, 166);           // teal accent strip
  doc.rect(0, 35, W, 4, 'F');

  // Logo text
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text('Alexandria', MARGIN, 22);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(199, 210, 254);          // indigo-200
  doc.text('AI Video Learning Companion  ·  Study Notes', MARGIN, 31);

  y = 52;

  // ─── LECTURE TITLE ────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(30, 27, 75);
  const titleLines = doc.splitTextToSize(title || 'Lecture Notes', CONTENT_W);
  doc.text(titleLines, MARGIN, y);
  y += titleLines.length * 8 + 4;

  // date line
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 150);
  doc.text(`Generated on ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`, MARGIN, y);
  y += 12;

  // divider
  doc.setDrawColor(224, 231, 255);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, y, W - MARGIN, y);
  y += 10;

  // ─── OVERVIEW ─────────────────────────────────────────────────────────────
  if (overall) {
    checkPage(18);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(99, 102, 241);
    doc.text('📋  Overview', MARGIN, y);
    y += 7;

    // light box bg
    const overallLines = doc.splitTextToSize(overall, CONTENT_W - 4);
    const boxH = overallLines.length * 6.5 + 8;
    doc.setFillColor(238, 242, 255);
    doc.roundedRect(MARGIN, y, CONTENT_W, boxH, 3, 3, 'F');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(55, 48, 163);
    doc.text(overallLines, MARGIN + 4, y + 6);
    y += boxH + 10;
  }

  // ─── TOPIC-WISE NOTES ─────────────────────────────────────────────────────
  if (topics && topics.length > 0) {
    checkPage(18);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(99, 102, 241);
    doc.text('📚  Topic-Wise Notes', MARGIN, y);
    y += 9;

    topics.forEach((t, i) => {
      const summaryLines = doc.splitTextToSize(t.summary || '', CONTENT_W - 14);
      const blockH = 8 + summaryLines.length * 6 + 6;
      checkPage(blockH + 4);

      // topic card background
      const isEven = i % 2 === 0;
      doc.setFillColor(isEven ? 245 : 240, isEven ? 247 : 253, isEven ? 255 : 255);
      doc.roundedRect(MARGIN, y, CONTENT_W, blockH, 2.5, 2.5, 'F');

      // left accent stripe
      doc.setFillColor(99, 102, 241);
      doc.rect(MARGIN, y, 3, blockH, 'F');

      // topic number badge
      doc.setFillColor(224, 231, 255);
      doc.roundedRect(MARGIN + 6, y + 3, 6, 6, 1, 1, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      doc.setTextColor(99, 102, 241);
      doc.text(String(i + 1), MARGIN + 9, y + 7.5, { align: 'center' });

      // topic title
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(30, 27, 75);
      const topicLabel = doc.splitTextToSize(t.topic || `Topic ${i + 1}`, CONTENT_W - 36);
      doc.text(topicLabel, MARGIN + 14, y + 7.5);

      // timestamp chip
      if (t.timestamp !== undefined) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(100, 116, 139);
        doc.text(`⏱ ${formatTime(t.timestamp)}`, W - MARGIN - 2, y + 7.5, { align: 'right' });
      }

      // summary text
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(71, 85, 105);
      doc.text(summaryLines, MARGIN + 14, y + 15);

      y += blockH + 4;
    });

    y += 4;
  }

  // ─── RECENT CONTEXT ───────────────────────────────────────────────────────
  if (recent && recent !== 'Awaiting more lecture data for recent summary...') {
    checkPage(18);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(20, 184, 166);
    doc.text('🕐  Last Section Summary', MARGIN, y);
    y += 7;

    const recentLines = doc.splitTextToSize(recent, CONTENT_W - 4);
    const boxH = recentLines.length * 6.5 + 8;
    doc.setFillColor(240, 253, 250);
    doc.roundedRect(MARGIN, y, CONTENT_W, boxH, 3, 3, 'F');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(15, 118, 110);
    doc.text(recentLines, MARGIN + 4, y + 6);
    y += boxH + 10;
  }

  // ─── LEARNING OUTCOMES ────────────────────────────────────────────────────
  if (topics && topics.length > 0) {
    checkPage(20);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(99, 102, 241);
    doc.text('🎯  Learning Outcomes', MARGIN, y);
    y += 8;

    topics.slice(0, 5).forEach((t, i) => {
      checkPage(9);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9.5);
      doc.setTextColor(51, 65, 85);
      const outcome = `${i + 1}. Understand and apply: ${t.topic}`;
      const lines = doc.splitTextToSize(outcome, CONTENT_W - 8);
      doc.text(lines, MARGIN + 4, y);
      y += lines.length * 6.5;
    });

    y += 6;
  }

  // ─── GLOSSARY ─────────────────────────────────────────────────────────────
  if (topics && topics.length > 0) {
    checkPage(20);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(99, 102, 241);
    doc.text('📖  Key Terms Glossary', MARGIN, y);
    y += 8;

    topics.forEach((t, i) => {
      checkPage(11);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(30, 27, 75);
      doc.text(`• ${t.topic}`, MARGIN + 2, y);

      const defLines = doc.splitTextToSize(
        t.summary ? t.summary.substring(0, 120) + (t.summary.length > 120 ? '…' : '') : '',
        CONTENT_W - 14
      );
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 116, 139);
      doc.text(defLines, MARGIN + 10, y + 5.5);
      y += 5.5 + defLines.length * 5.5 + 3;
    });
  }

  // ─── FINAL FOOTER on last page ────────────────────────────────────────────
  addFooter(pageNum);

  return doc;
}

// ─── component ───────────────────────────────────────────────────────────────

export default function PdfExport({ title, overall, topics, recent }) {
  const [status, setStatus] = useState('idle'); // idle | generating | done

  const canExport = Boolean(overall || (topics && topics.length > 0));

  async function handleExport() {
    if (!canExport || status === 'generating') return;
    setStatus('generating');
    try {
      await new Promise(r => setTimeout(r, 80)); // let React repaint
      const doc = buildPdf({ title, overall, topics, recent });
      const safeTitle = (title || 'lecture-notes').replace(/[^a-z0-9]/gi, '-').toLowerCase().slice(0, 40);
      doc.save(`${safeTitle}.pdf`);
      setStatus('done');
      setTimeout(() => setStatus('idle'), 2500);
    } catch (err) {
      console.error('PDF generation failed:', err);
      setStatus('idle');
      alert('PDF generation failed. Please try again.');
    }
  }

  return (
    <button
      id="pdf-export-btn"
      onClick={handleExport}
      disabled={!canExport || status === 'generating'}
      title={canExport ? 'Download study notes as PDF' : 'Waiting for summary to load…'}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.5rem',
        padding: '0.55rem 1.1rem',
        borderRadius: '10px',
        border: 'none',
        cursor: canExport && status !== 'generating' ? 'pointer' : 'not-allowed',
        fontWeight: 600,
        fontSize: '0.85rem',
        transition: 'all 0.2s ease',
        background: status === 'done'
          ? 'linear-gradient(135deg, #10b981, #059669)'
          : canExport
            ? 'linear-gradient(135deg, #6366f1, #8b5cf6)'
            : 'var(--surface-container)',
        color: canExport ? '#fff' : 'var(--text-secondary)',
        opacity: !canExport ? 0.6 : 1,
        boxShadow: canExport ? '0 4px 14px rgba(99,102,241,0.35)' : 'none',
      }}
      onMouseEnter={e => { if (canExport && status === 'idle') e.currentTarget.style.transform = 'translateY(-1px)'; }}
      onMouseLeave={e => { e.currentTarget.style.transform = 'translateY(0)'; }}
    >
      {status === 'generating' && <Loader2 size={15} className="animate-spin" />}
      {status === 'done'       && <CheckCircle size={15} />}
      {status === 'idle'       && <Download size={15} />}
      {status === 'generating' ? 'Building PDF…' : status === 'done' ? 'Downloaded!' : 'Download Notes PDF'}
    </button>
  );
}
